### ISSUE TITLE
ITUC and GSI Descriptions

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/EmbodiedSuffering_Toolkit#41]
#### Description:

**Updates to Descriptions for ITUC and GSI:**

ITUC’s Global Rights Index Data: 
The Freedom of Association indicator is derived from the ITUC Global Rights Index, published in 2021. Each of the countries were rated by ITUC on the likelihood that violations would be committed against workers' rights, scoring them on a scale from best to worst (1-5+). The rating indicates whether workers are prevented from certain rights and civil liberties like the right to strike, collective bargaining freedom, the right to unionize, the ability to pursue justice, free speech and assembly, and worker safety from retaliation and violent attacks. In the tool, countries are rated on a scale from 1-6. The score above represents the average ITUC value across the countries within your material's supply chains.

Global Slavery Index Data: 
The Victims of Modern Slavery indicator is derived from the Global Slavery Index that was published in 2018. GSI estimates the number of people in modern slavery in a country's population (# of victims per 1000 people). These figures are generated from Gallup World Poll surveys from 48 countries covering forced work, debt bondage, forced marriage and child labor. Additional surveys, and predictor variables like age, gender, corruption in government, and urbanicity were also used to estimate the number of victims of modern slavery. The score above represents the average GSI value across the countries within your material's supply chains.

@LLOUIE19

**Comment by adecler** [comment]
Issue solved in this PR: https://github.com/BuroHappoldEngineering/EmbodiedSuffering_Tool/pull/6
